# This workflow will run test and upload the coverage when push or pull_request is made on `dev` branch
name: Test and coverage

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Run Test and get coverage
        run: go test -race -covermode atomic -coverprofile=covprofile

      - name: Install goveralls
        if: success()
        run: GO111MODULE=on go get github.com/mattn/goveralls@latest

      - name: Push test coverage 1
        if: success()
        continue-on-error: true
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push test coverage 2
        if: success()
        continue-on-error: true
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github

      - name: Push test coverage 3
        if: success()
        continue-on-error: true
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: covprofile

