# This workflow will run test and upload the coverage when push or pull_request is made on `dev` branch
name: build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      # add this step for go 1.10 !!!!!!!!!!!!
      - name: Set up GOPATH
        run: |
          echo "GOPATH=${{ github.workspace }}" 
          echo "${{ github.workspace }}/bin"
          echo "PWD"
          pwd
          
          echo "GOPATH=${{ github.workspace }}" >> "$GITHUB_ENV"
          echo "${{ github.workspace }}/bin" >> "$GITHUB_PATH

      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Run Test and get coverage
        run: go test -race -covermode atomic -coverprofile=covprofile
        working-directory: src/example.com/owner/repo # add this !!!!!!!!!!!!

      - name: Install goveralls
        if: success()
        run: |
          echo "PWD"
          pwd
          GO111MODULE=on go install github.com/mattn/goveralls@latest
        # run: GO111MODULE=on go get github.com/mattn/goveralls@latest

      - name: Push test coverage 0
        if: success()
        continue-on-error: true
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "PWD"
          pwd
          goveralls -coverprofile=covprofile -service=github
        working-directory: src/example.com/owner/repo # add this !!!!!!!!!!!

      - name: Push test coverage 1
        if: success()
        continue-on-error: true
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push test coverage 2
        if: success()
        continue-on-error: true
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "PWD"
          pwd
          cd $GOPATH/src/github.com/yourusername/yourpackage
          goveralls -coverprofile=covprofile -service=github

      - name: Push test coverage 3
        if: success()
        continue-on-error: true
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: covprofile

